### ISSUE TITLE
Automatic steamworks without the 100% success rate?

### ISSUE THREAD

**Issue by regunakyle** [AdiBorsos/AutoSteamworks#9]
Hello,
Your mod works wonderfully! Its much faster than my own autohotkey script (lol).
However, I don't want to have 100% success rate because it feels like cheating.
Can you implement a option to use random pattern?
I know there is a UseRandomPattern option but it only works if the app is outdated.

**Comment by jrtaclas** [comment]
This program was made to read from memory to get the exact pattern, meaning the target is to get 100% accuracy.

If you don't want to cheat. DO NOT USE this or any MODS.

**Comment by tristam92** [comment]
Real implication of this feature is more like, farming items with low requirements. For example Megahealing potion. Which requires not full pattern to be entered. But because in-app input method is slow to response, it's actually better to allow this option work in latest version too. In that case you can speed up farm for non-100% items. as well

**Comment by AdiBorsos** [comment]
A Random option has been added to the application
